version: '3.7'
services:
  web:
    image: persistentcontainerregistry.azurecr.io/brothinjord.client
    container_name: zakolik_client_prod
    build:
      context: .
      dockerfile: Production.Dockerfile
      target: production
    environment:
      - CONTEXT=
      - PORT=150
    ports:
      - '4200:150'
