version: '3.5'

services:

  client:
    container_name: client
    build:
      context: ./client/
      dockerfile: Dockerfile
      target: development
    volumes:
      - './client:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - '4200:4200'
    environment:
      - NODE_ENV=development

  server:
    container_name: server
    restart: always
    build:
      context: ./server/
      dockerfile: Dockerfile
    volumes:
      - './server:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - '4000:4000'
    links:
      - database
    environment:
      - NODE_ENV=development

  database:
    container_name: database
    image: postgres:alpine
    restart: always
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    env_file:
      - server/development.env
