version: '3.7'
services:
  web:
    image: persistentcontainerregistry.azurecr.io/brothinjord.client
    container_name: zakolik_client_prod
    build:
      context: ./client/
      dockerfile: Dockerfile
      target: production
    environment:
      - PORT=80
    ports:
      - "80:80"
      - "443:443"
    links:
      - server
    volumes:
      - /home/zakolik/zakolik/client/nginx.conf:/etc/nginx/nginx.conf
      - certbot-webroot-zakolik:/usr/share/nginx/html/.well-known
      - certbot-letsencrypt:/etc/letsencrypt

  certbot:
    build: ./certbot
    container_name: certbot
    restart: always
    volumes:
      - certbot-webroot-zakolik:/webroots/zakolik.eu/.well-known
      - certbot-letsencrypt:/etc/letsencrypt

  server:
    container_name: zakolik_server_prod
    restart: always
    build:
      context: ./server/
      dockerfile: Dockerfile
      target: production
    volumes:
      - certbot-letsencrypt:/etc/letsencrypt

    ports:
#      - '23450:23450'
      - '23451:23451'
    links:
      - database
    environment:
      - NODE_ENV=production

  database:
    container_name: zakolik_database_prod
    image: postgres:alpine
    restart: always
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - server/production.env

volumes:
  certbot-webroot-zakolik:
  certbot-letsencrypt:
